## ########################################################################## ##
## Author: db0 (db0company@gmail.com, http://db0.fr/)                         ##
## ########################################################################## ##

all:
	ocamlfind ocamlc -o check_invite -package str,curl,yojson -I ../ ../consumer.mli ../consumer.ml invite.ml -linkpkg
